name: Workflow Dispatch using Choice type 

on:
  workflow_dispatch:
    inputs: 
      vm:
        description: Select the Virtual Machine
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest

jobs:
  test:
    runs-on: ${{ github.event.inputs.vm }}    
    # if: ${{ github.event.inputs.vm == 'ubuntu-latest' }}
    steps:
      - run: echo "This task is run on ${{ github.event.inputs.vm }}"
